name: bombernyaa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^5.2.0
  google_fonts: ^3.0.1
  injectable: ^2.0.0
  injectable_generator: ^2.0.0
  json_annotation: ^4.7.0
  velocity_x: ^3.6.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true