name: bombernyaa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  awesome_dialog: ^2.1.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  go_router: ^3.0.6
  injectable: ^1.5.0
  injectable_generator: ^1.5.2
  json_annotation: ^4.4.0
  velocity_x: ^3.3.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true